In [3]:
import pandas as pd

In [5]:
#opening the csv file and reading it, assigning the contents to the variable file

file = open("gdp_europe.csv").read()

In [6]:
print(file[:400])

country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.00391,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.59803,10750.72111,12834.6024,16661.6

In [11]:
#Using pandas to open a dataframe from the contents of the csv file gdp_africa.csv. 
#Saving the contents of the csv file to variable df

df = pd.read_csv("gdp_europe.csv", index_col=0)

In [12]:
print(df)

                        gdpPercap_1952  gdpPercap_1957  gdpPercap_1962
country
Albania                    1601.056136     1942.284244     2312.888958  \
Austria                    6137.076492     8842.598030    10750.721110
Belgium                    8343.105127     9714.960623    10991.206760
Bosnia and Herzegovina      973.533195     1353.989176     1709.683679
Bulgaria                   2444.286648     3008.670727     4254.337839
Croatia                    3119.236520     4338.231617     5477.890018
Czech Republic             6876.140250     8256.343918    10136.867130
Denmark                    9692.385245    11099.659350    13583.313510
Finland                    6424.519071     7545.415386     9371.842561
France                     7029.809327     8662.834898    10560.485530
Germany                    7144.114393    10187.826650    12902.462910
Greece                     3530.690067     4916.299889     6017.190733
Hungary                    5263.673816     6040.180011     7550.359877
Iceland                    7267.688428     9244.001412    10350.159060
Ireland                    5210.280328     5599.077872     6631.597314
Italy                      4931.404155     6248.656232     8243.582340
Montenegro                 2647.585601     3682.259903     4649.593785
Netherlands                8941.571858    11276.193440    12790.849560
Norway                    10095.421720    11653.973040    13450.401510
Poland                     4029.329699     4734.253019     5338.752143
Portugal                   3068.319867     3774.571743     4727.954889
Romania                    3144.613186     3943.370225     4734.997586
Serbia                     3581.459448     4981.090891     6289.629157
Slovak Republic            5074.659104     6093.262980     7481.107598
Slovenia                   4215.041741     5862.276629     7402.303395
Spain                      3834.034742     4564.802410     5693.843879
Sweden                     8527.844662     9911.878226    12329.441920
Switzerland               14734.232750    17909.489730    20431.092700
Turkey                     1969.100980     2218.754257     2322.869908
United Kingdom             9979.508487    11283.177950    12477.177070

                        gdpPercap_1967  gdpPercap_1972  gdpPercap_1977
country
Albania                    2760.196931     3313.422188     3533.003910  \
Austria                   12834.602400    16661.625600    19749.422300
Belgium                   13149.041190    16672.143560    19117.974480
Bosnia and Herzegovina     2172.352423     2860.169750     3528.481305
Bulgaria                   5577.002800     6597.494398     7612.240438
Croatia                    6960.297861     9164.090127    11305.385170
Czech Republic            11399.444890    13108.453600    14800.160620
Denmark                   15937.211230    18866.207210    20422.901500
Finland                   10921.636260    14358.875900    15605.422830
France                    12999.917660    16107.191710    18292.635140
Germany                   14745.625610    18016.180270    20512.921230
Greece                     8513.097016    12724.829570    14195.524280
Hungary                    9326.644670    10168.656110    11674.837370
Iceland                   13319.895680    15798.063620    19654.962470
Ireland                    7655.568963     9530.772896    11150.981130
Italy                     10022.401310    12269.273780    14255.984750
Montenegro                 5907.850937     7778.414017     9595.929905
Netherlands               15363.251360    18794.745670    21209.059200
Norway                    16361.876470    18965.055510    23311.349390
Poland                     6557.152776     8006.506993     9508.141454
Portugal                   6361.517993     9022.247417    10172.485720
Romania                    6470.866545     8011.414402     9356.397240
Serbia                     7991.707066    10522.067490    12980.669560
Slovak Republic            8412.902397     9674.167626    10922.664040
Slovenia                   9405.489397    12383.486200    15277.030170
Spain                      7993.512294    10638.751310    13236.921170
Sweden                    15258.296970    17832.024640    18855.725210
Switzerland               22966.144320    27195.113040    26982.290520
Turkey                     2826.356387     3450.696380     4269.122326
United Kingdom            14142.850890    15895.116410    17428.748460

                        gdpPercap_1982  gdpPercap_1987  gdpPercap_1992
country
Albania                    3630.880722     3738.932735     2497.437901  \
Austria                   21597.083620    23687.826070    27042.018680
Belgium                   20979.845890    22525.563080    25575.570690
Bosnia and Herzegovina     4126.613157     4314.114757     2546.781445
Bulgaria                   8224.191647     8239.854824     6302.623438
Croatia                   13221.821840    13822.583940     8447.794873
Czech Republic            15377.228550    16310.443400    14297.021220
Denmark                   21688.040480    25116.175810    26406.739850
Finland                   18533.157610    21141.012230    20647.164990
France                    20293.897460    22066.442140    24703.796150
Germany                   22031.532740    24639.185660    26505.303170
Greece                    15268.420890    16120.528390    17541.496340
Hungary                   12545.990660    12986.479980    10535.628550
Iceland                   23269.607500    26923.206280    25144.392010
Ireland                   12618.321410    13872.866520    17558.815550
Italy                     16537.483500    19207.234820    22013.644860
Montenegro                11222.587620    11732.510170     7003.339037
Netherlands               21399.460460    23651.323610    26790.949610
Norway                    26298.635310    31540.974800    33965.661150
Poland                     8451.531004     9082.351172     7738.881247
Portugal                  11753.842910    13039.308760    16207.266630
Romania                    9605.314053     9696.273295     6598.409903
Serbia                    15181.092700    15870.878510     9325.068238
Slovak Republic           11348.545850    12037.267580     9498.467723
Slovenia                  17866.721750    18678.534920    14214.716810
Spain                     13926.169970    15764.983130    18603.064520
Sweden                    20667.381250    23586.929270    23880.016830
Switzerland               28397.715120    30281.704590    31871.530300
Turkey                     4241.356344     5089.043686     5678.348271
United Kingdom            18232.424520    21664.787670    22705.092540

                        gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Albania                    3193.054604     4604.211737     5937.029526
Austria                   29095.920660    32417.607690    36126.492700
Belgium                   27561.196630    30485.883750    33692.605080
Bosnia and Herzegovina     4766.355904     6018.975239     7446.298803
Bulgaria                   5970.388760     7696.777725    10680.792820
Croatia                    9875.604515    11628.388950    14619.222720
Czech Republic            16048.514240    17596.210220    22833.308510
Denmark                   29804.345670    32166.500060    35278.418740
Finland                   23723.950200    28204.590570    33207.084400
France                    25889.784870    28926.032340    30470.016700
Germany                   27788.884160    30035.801980    32170.374420
Greece                    18747.698140    22514.254800    27538.411880
Hungary                   11712.776800    14843.935560    18008.944440
Iceland                   28061.099660    31163.201960    36180.789190
Ireland                   24521.947130    34077.049390    40675.996350
Italy                     24675.024460    27968.098170    28569.719700
Montenegro                 6465.613349     6557.194282     9253.896111
Netherlands               30246.130630    33724.757780    36797.933320
Norway                    41283.164330    44683.975250    49357.190170
Poland                    10159.583680    12002.239080    15389.924680
Portugal                  17641.031560    19970.907870    20509.647770
Romania                    7346.547557     7885.360081    10808.475610
Serbia                     7914.320304     7236.075251     9786.534714
Slovak Republic           12126.230650    13638.778370    18678.314350
Slovenia                  17161.107350    20660.019360    25768.257590
Spain                     20445.298960    24835.471660    28821.063700
Sweden                    25266.594990    29341.630930    33859.748350
Switzerland               32135.323010    34480.957710    37506.419070
Turkey                     6601.429915     6508.085718     8458.276384
United Kingdom            26074.531360    29478.999190    33203.261280

In [13]:
#printing the first three rows of the dataframe

df.head(3)

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.00391,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.42230,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.97448,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080

In [14]:
#Getting summary info about the dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, Albania to United Kingdom
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gdpPercap_1952  30 non-null     float64
 1   gdpPercap_1957  30 non-null     float64
 2   gdpPercap_1962  30 non-null     float64
 3   gdpPercap_1967  30 non-null     float64
 4   gdpPercap_1972  30 non-null     float64
 5   gdpPercap_1977  30 non-null     float64
 6   gdpPercap_1982  30 non-null     float64
 7   gdpPercap_1987  30 non-null     float64
 8   gdpPercap_1992  30 non-null     float64
 9   gdpPercap_1997  30 non-null     float64
 10  gdpPercap_2002  30 non-null     float64
 11  gdpPercap_2007  30 non-null     float64
dtypes: float64(12)
memory usage: 3.0+ KB

In [15]:
#Getting summary statistics about the dataframe

df.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,5661.057435,6963.012816,8365.486814,10143.823757,12479.575246,14283.979110,15617.896551,17214.310727,17061.568084,19076.781802,21711.732422,25054.481636
std,3114.060493,3677.950146,4199.193906,4724.983889,5509.691411,5874.464896,6453.234827,7482.957960,9109.804361,10065.457716,11197.355517,11800.339811
min,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
25%,3241.132406,4394.874315,5373.536612,6657.939047,9057.708094,10360.030300,11449.870115,12274.570680,8667.113214,9946.599306,11721.851483,14811.898210
50%,5142.469716,6066.721495,7515.733737,9366.067033,12326.379990,14225.754515,15322.824720,16215.485895,17550.155945,19596.498550,23674.863230,28054.065790
75%,7236.794919,9597.220820,10931.085348,13277.182058,16523.017127,19052.412163,20901.729730,23321.587723,25034.243045,27189.530312,30373.363307,33817.962533
max,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170

In [16]:
#Slicing a column of the dataframe

df["gdpPercap_1952"]

country
Albania                    1601.056136
Austria                    6137.076492
Belgium                    8343.105127
Bosnia and Herzegovina      973.533195
Bulgaria                   2444.286648
Croatia                    3119.236520
Czech Republic             6876.140250
Denmark                    9692.385245
Finland                    6424.519071
France                     7029.809327
Germany                    7144.114393
Greece                     3530.690067
Hungary                    5263.673816
Iceland                    7267.688428
Ireland                    5210.280328
Italy                      4931.404155
Montenegro                 2647.585601
Netherlands                8941.571858
Norway                    10095.421720
Poland                     4029.329699
Portugal                   3068.319867
Romania                    3144.613186
Serbia                     3581.459448
Slovak Republic            5074.659104
Slovenia                   4215.041741
Spain                      3834.034742
Sweden                     8527.844662
Switzerland               14734.232750
Turkey                     1969.100980
United Kingdom             9979.508487
Name: gdpPercap_1952, dtype: float64

In [17]:
#Slicing two columns--note the double square brackets

df[["gdpPercap_1952", "gdpPercap_1962"]]

                        gdpPercap_1952  gdpPercap_1962
country
Albania                    1601.056136     2312.888958
Austria                    6137.076492    10750.721110
Belgium                    8343.105127    10991.206760
Bosnia and Herzegovina      973.533195     1709.683679
Bulgaria                   2444.286648     4254.337839
Croatia                    3119.236520     5477.890018
Czech Republic             6876.140250    10136.867130
Denmark                    9692.385245    13583.313510
Finland                    6424.519071     9371.842561
France                     7029.809327    10560.485530
Germany                    7144.114393    12902.462910
Greece                     3530.690067     6017.190733
Hungary                    5263.673816     7550.359877
Iceland                    7267.688428    10350.159060
Ireland                    5210.280328     6631.597314
Italy                      4931.404155     8243.582340
Montenegro                 2647.585601     4649.593785
Netherlands                8941.571858    12790.849560
Norway                    10095.421720    13450.401510
Poland                     4029.329699     5338.752143
Portugal                   3068.319867     4727.954889
Romania                    3144.613186     4734.997586
Serbia                     3581.459448     6289.629157
Slovak Republic            5074.659104     7481.107598
Slovenia                   4215.041741     7402.303395
Spain                      3834.034742     5693.843879
Sweden                     8527.844662    12329.441920
Switzerland               14734.232750    20431.092700
Turkey                     1969.100980     2322.869908
United Kingdom             9979.508487    12477.177070

In [18]:
#Getting a particular cell's value based on column and row headings

df.loc["Belgium", "gdpPercap_1952"]

8343.105127

In [19]:
#Slicing a row of a dataframe--note the difference to slicing a column

df.loc["Belgium"]

gdpPercap_1952     8343.105127
gdpPercap_1957     9714.960623
gdpPercap_1962    10991.206760
gdpPercap_1967    13149.041190
gdpPercap_1972    16672.143560
gdpPercap_1977    19117.974480
gdpPercap_1982    20979.845890
gdpPercap_1987    22525.563080
gdpPercap_1992    25575.570690
gdpPercap_1997    27561.196630
gdpPercap_2002    30485.883750
gdpPercap_2007    33692.605080
Name: Belgium, dtype: float64

In [20]:
#Getting a subset of data using a slice of both rows and columns

df.loc['Italy':'Poland', 'gdpPercap_1962':'gdpPercap_1972']

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy           8243.582340    10022.401310    12269.273780
Montenegro      4649.593785     5907.850937     7778.414017
Netherlands    12790.849560    15363.251360    18794.745670
Norway         13450.401510    16361.876470    18965.055510
Poland          5338.752143     6557.152776     8006.506993

In [21]:
#Find the minimum value in a particular row

df.loc["Belgium"].min()

8343.105127

In [22]:
#Find the minimum value in a particular row

df.loc["Belgium"].max()

33692.60508

In [23]:
#Get the mean GDP of the entire dataset

df.mean()

gdpPercap_1952     5661.057435
gdpPercap_1957     6963.012816
gdpPercap_1962     8365.486814
gdpPercap_1967    10143.823757
gdpPercap_1972    12479.575246
gdpPercap_1977    14283.979110
gdpPercap_1982    15617.896551
gdpPercap_1987    17214.310727
gdpPercap_1992    17061.568084
gdpPercap_1997    19076.781802
gdpPercap_2002    21711.732422
gdpPercap_2007    25054.481636
dtype: float64

In [24]:
#Get the mean value of a particular column

df["gdpPercap_1952"].mean()

5661.0574347599995

In [27]:
#Extracting the names of the columns and rows

countries = df.index.values
years = df.columns.values

In [28]:
print(countries)
print(years)

['Albania' 'Austria' 'Belgium' 'Bosnia and Herzegovina' 'Bulgaria'
 'Croatia' 'Czech Republic' 'Denmark' 'Finland' 'France' 'Germany'
 'Greece' 'Hungary' 'Iceland' 'Ireland' 'Italy' 'Montenegro' 'Netherlands'
 'Norway' 'Poland' 'Portugal' 'Romania' 'Serbia' 'Slovak Republic'
 'Slovenia' 'Spain' 'Sweden' 'Switzerland' 'Turkey' 'United Kingdom']
['gdpPercap_1952' 'gdpPercap_1957' 'gdpPercap_1962' 'gdpPercap_1967'
 'gdpPercap_1972' 'gdpPercap_1977' 'gdpPercap_1982' 'gdpPercap_1987'
 'gdpPercap_1992' 'gdpPercap_1997' 'gdpPercap_2002' 'gdpPercap_2007']